global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@judge-system.local'
  slack_api_url: 'YOUR_SLACK_API_URL_HERE'  # Replace with actual Slack webhook URL

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 15m
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      repeat_interval: 1h
    - match:
        service: judge
      receiver: 'judge-specific-alerts'
      group_wait: 15s
      repeat_interval: 30m

receivers:
  - name: 'default-notifications'
    webhook_configs:
      - url: 'http://localhost:5001/webhook'
        send_resolved: true
        title: 'Judge System Alert'
        text: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Status: {{ .Status }}
          Labels: {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}
          {{ end }}

  - name: 'critical-alerts'
    slack_configs:
      - api_url: 'YOUR_SLACK_API_URL_HERE'  # Replace with actual Slack webhook URL
        channel: '#alerts-critical'
        username: 'Judge System Monitor'
        icon_emoji: ':fire:'
        title: '🚨 CRITICAL ALERT: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Service:* {{ .Labels.service }}
          *Instance:* {{ .Labels.instance }}
          *Status:* {{ .Status }}
          *Time:* {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}
        send_resolved: true
        actions:
          - type: button
            text: 'View in Grafana'
            url: 'http://localhost:3000/d/judge-system-overview'
    webhook_configs:
      - url: 'http://localhost:5001/webhook/critical'
        send_resolved: true
        title: 'CRITICAL: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        text: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Instance: {{ .Labels.instance }}
          Status: {{ .Status }}
          Time: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}

  - name: 'warning-alerts'
    slack_configs:
      - api_url: 'YOUR_SLACK_API_URL_HERE'  # Replace with actual Slack webhook URL
        channel: '#alerts-warning'
        username: 'Judge System Monitor'
        icon_emoji: ':warning:'
        title: '⚠️ WARNING: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Service:* {{ .Labels.service }}
          *Instance:* {{ .Labels.instance }}
          *Status:* {{ .Status }}
          *Time:* {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}
        send_resolved: true
    webhook_configs:
      - url: 'http://localhost:5001/webhook/warning'
        send_resolved: true
        title: 'WARNING: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        text: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Instance: {{ .Labels.instance }}
          Status: {{ .Status }}
          Time: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}

  - name: 'judge-specific-alerts'
    slack_configs:
      - api_url: 'YOUR_SLACK_API_URL_HERE'  # Replace with actual Slack webhook URL
        channel: '#judge-system'
        username: 'Judge System Monitor'
        icon_emoji: ':scales:'
        title: '⚖️ Judge System Alert: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Queue:* {{ .Labels.queue }}
          *Severity:* {{ .Labels.severity }}
          *Status:* {{ .Status }}
          *Time:* {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}
        send_resolved: true
    webhook_configs:
      - url: 'http://localhost:5001/webhook/judge'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']