groups:
  - name: judge_system_alerts
    rules:
      # High API latency alert (100ms threshold as specified)
      - alert: HighAPILatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="api-server"}[5m])) > 0.1
        for: 2m
        labels:
          severity: warning
          service: api
        annotations:
          summary: "High API latency detected"
          description: "95th percentile latency is {{ $value | humanizeDuration }} for {{ $labels.instance }}"

      # Critical API latency alert
      - alert: CriticalAPILatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="api-server"}[5m])) > 0.5
        for: 1m
        labels:
          severity: critical
          service: api
        annotations:
          summary: "Critical API latency detected"
          description: "95th percentile latency is {{ $value | humanizeDuration }} for {{ $labels.instance }}"

      # High error rate alert
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
        for: 1m
        labels:
          severity: critical
          service: api
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for {{ $labels.instance }}"

      # Judge queue backup alert
      - alert: JudgeQueueBackup
        expr: sum(asynq_queue_size{queue="default"}) > 50
        for: 2m
        labels:
          severity: warning
          service: judge
          queue: default
        annotations:
          summary: "Judge queue backup detected"
          description: "Default judge queue has {{ $value }} pending submissions"

      # Critical judge queue backup alert
      - alert: CriticalJudgeQueueBackup
        expr: sum(asynq_queue_size{queue="default"}) > 200
        for: 1m
        labels:
          severity: critical
          service: judge
          queue: default
        annotations:
          summary: "Critical judge queue backup detected"
          description: "Default judge queue has {{ $value }} pending submissions - immediate attention required"

      # Critical priority queue backup alert
      - alert: CriticalQueueBackup
        expr: sum(asynq_queue_size{queue="critical"}) > 10
        for: 1m
        labels:
          severity: critical
          service: judge
          queue: critical
        annotations:
          summary: "Critical priority queue backup detected"
          description: "Critical queue has {{ $value }} pending submissions"

      # High memory usage alert
      - alert: HighMemoryUsage
        expr: (container_memory_usage_bytes / container_spec_memory_limit_bytes) > 0.9
        for: 1m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is {{ $value | humanizePercentage }} for {{ $labels.container_label_com_docker_compose_service }}"

      # High CPU usage alert
      - alert: HighCPUUsage
        expr: rate(container_cpu_usage_seconds_total[5m]) > 0.8
        for: 2m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is {{ $value | humanizePercentage }} for {{ $labels.container_label_com_docker_compose_service }}"

      # Database connection failures
      - alert: DatabaseConnectionFailure
        expr: increase(postgres_connection_errors_total[5m]) > 5
        for: 1m
        labels:
          severity: critical
          service: database
        annotations:
          summary: "Database connection failures detected"
          description: "{{ $value }} database connection failures in the last 5 minutes"

      # Redis connection failures
      - alert: RedisConnectionFailure
        expr: redis_connected_clients == 0
        for: 1m
        labels:
          severity: critical
          service: redis
        annotations:
          summary: "Redis connection failure detected"
          description: "No Redis clients connected"

      # Service down alert
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "Service is down"
          description: "{{ $labels.job }} on {{ $labels.instance }} is down"