global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'judge-system'
    environment: 'development'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Judge Worker Service (Health and metrics endpoints)
  - job_name: 'judge-worker-health'
    static_configs:
      - targets: ['judge-worker:8081']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 10s

  # Judge Worker Service (Dedicated metrics endpoint)
  - job_name: 'judge-worker-metrics'
    static_configs:
      - targets: ['judge-worker:8082']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 10s

  # Main API Server
  - job_name: 'api-server'
    static_configs:
      - targets: ['api-server:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 10s

  # PostgreSQL Exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Node Exporter (for system metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Docker container metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s