apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: judge-worker-hpa
  namespace: competitive-programming
  labels:
    app: judge-worker
    component: autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: judge-worker
  
  # Scaling configuration
  minReplicas: 2
  maxReplicas: 20
  
  # Scaling policies
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max
    
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 1
        periodSeconds: 60
      selectPolicy: Min
  
  # Scaling metrics
  metrics:
  
  # CPU utilization
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  
  # Memory utilization
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  
  # Custom metric: Queue depth
  - type: Object
    object:
      metric:
        name: judge_queue_depth
      target:
        type: Value
        value: "10"
      describedObject:
        apiVersion: v1
        kind: Service
        name: redis-service
  
  # Custom metric: Active submissions per pod
  - type: Pods
    pods:
      metric:
        name: judge_active_submissions_per_pod
      target:
        type: AverageValue
        averageValue: "5"
  
  # External metric: Response time
  - type: External
    external:
      metric:
        name: judge_avg_response_time_seconds
        selector:
          matchLabels:
            service: judge-worker
      target:
        type: Value
        value: "2"

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: judge-worker-contest-hpa
  namespace: competitive-programming
  labels:
    app: judge-worker
    component: autoscaling
    mode: contest
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: judge-worker
  
  # Contest mode - more aggressive scaling
  minReplicas: 5
  maxReplicas: 50
  
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 200
        periodSeconds: 30
      - type: Pods
        value: 5
        periodSeconds: 30
      selectPolicy: Max
    
    scaleDown:
      stabilizationWindowSeconds: 600  # 10 minutes
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
  
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  
  - type: Object
    object:
      metric:
        name: judge_queue_depth
      target:
        type: Value
        value: "5"  # More sensitive in contest mode
      describedObject:
        apiVersion: v1
        kind: Service
        name: redis-service