apiVersion: v1
kind: ServiceAccount
metadata:
  name: judge-worker-sa
  namespace: competitive-programming
  labels:
    app: judge-worker
    component: security
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: judge-worker-cluster-role
  labels:
    app: judge-worker
    component: security
rules:
- apiGroups: [""]
  resources: ["nodes", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: judge-worker-cluster-role-binding
  labels:
    app: judge-worker
    component: security
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: judge-worker-cluster-role
subjects:
- kind: ServiceAccount
  name: judge-worker-sa
  namespace: competitive-programming
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: judge-worker-role
  namespace: competitive-programming
  labels:
    app: judge-worker
    component: security
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: judge-worker-role-binding
  namespace: competitive-programming
  labels:
    app: judge-worker
    component: security
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: judge-worker-role
subjects:
- kind: ServiceAccount
  name: judge-worker-sa
  namespace: competitive-programming