apiVersion: v1
kind: Secret
metadata:
  name: judge-worker-secrets
  namespace: competitive-programming
  labels:
    app: judge-worker
    component: security
type: Opaque
data:
  # Database credentials (base64 encoded)
  DATABASE_URL: cG9zdGdyZXM6Ly9qdWRnZTpwYXNzd29yZEBwb3N0Z3Jlcy1zZXJ2aWNlOjU0MzIvY29tcGV0aXRpdmVfcHJvZ3JhbW1pbmc/c3NsbW9kZT1kaXNhYmxl
  
  # Redis credentials (base64 encoded)
  REDIS_URL: cmVkaXM6Ly9yZWRpcy1zZXJ2aWNlOjYzNzkvMA==
  
  # JWT signing key (base64 encoded)
  JWT_SECRET: c3VwZXItc2VjcmV0LWp3dC1rZXktZm9yLXByb2R1Y3Rpb24=
  
  # Container registry credentials
  REGISTRY_USERNAME: anVkZ2UtcmVnaXN0cnk=
  REGISTRY_PASSWORD: c3VwZXItc2VjcmV0LXBhc3N3b3Jk
---
apiVersion: v1
kind: Secret
metadata:
  name: container-registry-secret
  namespace: competitive-programming
  labels:
    app: judge-worker
    component: security
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJyZWdpc3RyeS5leGFtcGxlLmNvbSI6IHsKICAgICAgInVzZXJuYW1lIjogImp1ZGdlLXJlZ2lzdHJ5IiwKICAgICAgInBhc3N3b3JkIjogInN1cGVyLXNlY3JldC1wYXNzd29yZCIsCiAgICAgICJhdXRoIjogImFuVmtaMlV0Y21WbmFYTjBjbms2YzNWd1pYSXRjMlZqY21WMExYQmhjM04zYjNKayIKICAgIH0KICB9Cn0=
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-certificates
  namespace: competitive-programming
  labels:
    app: judge-worker
    component: security
type: kubernetes.io/tls
data:
  # TLS certificate (base64 encoded)
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi4uLgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  
  # TLS private key (base64 encoded)  
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi4uLgotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0t