apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: judge-worker-vpa
  namespace: competitive-programming
  labels:
    app: judge-worker
    component: autoscaling
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: judge-worker
  
  updatePolicy:
    updateMode: "Auto"  # Auto, Initial, Off
    minReplicas: 2
  
  resourcePolicy:
    containerPolicies:
    - containerName: judge-worker
      mode: Auto
      minAllowed:
        cpu: 100m
        memory: 128Mi
        ephemeral-storage: 256Mi
      maxAllowed:
        cpu: 4000m
        memory: 8Gi
        ephemeral-storage: 4Gi
      controlledResources:
      - cpu
      - memory
      - ephemeral-storage
      controlledValues: RequestsAndLimits
    
    - containerName: metrics-exporter
      mode: Auto
      minAllowed:
        cpu: 10m
        memory: 32Mi
      maxAllowed:
        cpu: 100m
        memory: 128Mi
      controlledResources:
      - cpu
      - memory
      controlledValues: RequestsAndLimits

---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: postgres-vpa
  namespace: competitive-programming
  labels:
    app: postgres
    component: autoscaling
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: postgres
  
  updatePolicy:
    updateMode: "Initial"  # Only set initial values, don't update running pods
  
  resourcePolicy:
    containerPolicies:
    - containerName: postgres
      mode: Auto
      minAllowed:
        cpu: 250m
        memory: 512Mi
        ephemeral-storage: 1Gi
      maxAllowed:
        cpu: 4000m
        memory: 16Gi
        ephemeral-storage: 8Gi
      controlledResources:
      - cpu
      - memory
      - ephemeral-storage
      controlledValues: RequestsAndLimits

---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: redis-vpa
  namespace: competitive-programming
  labels:
    app: redis
    component: autoscaling
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: redis
  
  updatePolicy:
    updateMode: "Initial"
  
  resourcePolicy:
    containerPolicies:
    - containerName: redis
      mode: Auto
      minAllowed:
        cpu: 100m
        memory: 256Mi
        ephemeral-storage: 1Gi
      maxAllowed:
        cpu: 2000m
        memory: 4Gi
        ephemeral-storage: 4Gi
      controlledResources:
      - cpu
      - memory
      - ephemeral-storage
      controlledValues: RequestsAndLimits
    
    - containerName: redis-exporter
      mode: Auto
      minAllowed:
        cpu: 50m
        memory: 64Mi
      maxAllowed:
        cpu: 200m
        memory: 256Mi
      controlledResources:
      - cpu
      - memory
      controlledValues: RequestsAndLimits